[package]
name = "Horse_Race_Aptos"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
resource_publisher = "0x484b66004bbcf0939d0754a4f0e79ec24849e9363b996a12116cfa01d525a733"
publisher = "0xbb88df934986f37178d574f5c1ed643fe66d96c29375a7e8ba82eaa0f837d3f4" #in_unity

[dev-addresses]
publisher = "0xbb88df934986f37178d574f5c1ed643fe66d96c29375a7e8ba82eaa0f837d3f4"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-token-objects"