[package]
name = "Horse_Race_Aptos"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
resource_publisher = "0x101510bb574fbdd156d267b4832fe8bf461836f97681b797adac7720fc26f7e4"
publisher = "0x49c519a35b0c94a1825a1e493fdf6f2a3c5c3ad03ca1803327947d2f7740af78"

[dev-addresses]
publisher = "0x49c519a35b0c94a1825a1e493fdf6f2a3c5c3ad03ca1803327947d2f7740af78"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-token-objects"