[package]
name = "Horse_Race_Aptos"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
resource_publisher = "0x746e211677a9755df3b6397d2a0f513c4f6af82e6caaef2f1c032f3855f002c9"
publisher = "0xf5ba4eeade1e3505128e8e7ed36cb147aa4c1fb53ce5a11074ec32dd9f40195c" #in_unity

[dev-addresses]
publisher = "0xf5ba4eeade1e3505128e8e7ed36cb147aa4c1fb53ce5a11074ec32dd9f40195c"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-token-objects"