[package]
name = "Horse_Race_Aptos"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
resource_publisher = "0x81b1505ee9f9e646d98ad6447b0183fa4a6fed1509a6f3da8f0f09c338625ead"
publisher = "0xdafe19420f798da33a13a5928202ee55f812b1d4666aad6e0f66dedd6daefead" #in_unity

[dev-addresses]
publisher = "0xdafe19420f798da33a13a5928202ee55f812b1d4666aad6e0f66dedd6daefead"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-token-objects"